#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: alertd
# REQUIRE: datastore dispatcher

. /etc/rc.subr

name="alertd"
rcvar="alertd_enable"
pidfile="/var/run/alertd.pid"
command="/usr/sbin/daemon"
start_precmd="prestart"

prestart()
{
    rc_flags="-P ${pidfile} -f -r /usr/local/sbin/crash-wrapper /usr/local/sbin/alertd ${rc_flags}"
}

load_rc_config $name
run_rc_command $*
