#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: datastore

name="datastore"
rcvar="datastore_enable"
start_cmd="datastore_start"
init_cmd="datastore_init"
stop_cmd="datastore_stop"
extra_commands="init"
libdir="/usr/local/lib/datastore"

. /etc/rc.subr

datastore_start()
{
    /usr/local/sbin/dsinit --start-forked
}

datastore_stop()
{
    /usr/local/sbin/dsinit --stop-forked
}

datastore_init()
{
     /usr/local/sbin/dsinit --init
}

load_rc_config $name
run_rc_command $*
