#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: dispatcher
# REQUIRE: datastore
# BEFORE: FILESYSTEMS

. /etc/rc.subr

name="dispatcher"
rcvar="dispatcher_enable"
pidfile="/var/run/dispatcher.pid"
command="/usr/sbin/daemon"
start_precmd="prestart"
start_postcmd="poststart"
dispatcher_env="GEVENT_RESOLVER=ares"

prestart()
{
    rc_flags="-P ${pidfile} /usr/local/sbin/crash-wrapper /usr/local/sbin/dispatcherd ${rc_flags}"

   # mount .system dataset (or create it/fix links if needed)
   /usr/local/sbin/sdsinit

   if [ -z "$(check_pidfile /var/run/devd.pid /sbin/devd)" ]; then
        /sbin/devd
   fi

   if [ "$(check_pidfile /var/run/dispatcher.pid /usr/sbin/daemon)" ]; then
        echo "ERROR: dispatcher is already running"
        exit 1
   fi
}

poststart()
{
    # ensure that dispatcher is up and accepting connections.
    if ! /usr/local/sbin/dispatcherctl wait-server --timeout 180; then
        echo "ERROR: dispatcher failed to start"
        exit 1
    fi
}

load_rc_config $name
run_rc_command $*
