#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: debugd
# REQUIRE: datastore

. /etc/rc.subr

name="debugd"
rcvar="debugd_enable"
pidfile="/var/run/debugd.pid"
command="/usr/sbin/daemon"
start_precmd="prestart"

prestart()
{
    rc_flags="-P ${pidfile} -f -r /usr/local/sbin/crash-wrapper /usr/local/sbin/debugd ${rc_flags}"
}

load_rc_config $name
run_rc_command $*
