# $FreeBSD$

PORTNAME=	dockerpty
PORTVERSION=	0.4.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}six>1.3.0:${PORTSDIR}/devel/py-six

MAINTAINER=	jceel@FreeBSD.org
COMMENT=	Pseudo-tty handler for docker Python client.

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
