# $FreeBSD$

PORTNAME=	gssapi
PORTVERSION=	1.2.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
MAINTAINER=	dev@FreeBSD.org
COMMENT=	Python GSSAPI Wrapper

BUILD_DEPENDS=  ${LOCALBASE}/bin/cython:${PORTSDIR}/lang/cython

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
